# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["you@example.com"]
description = "Fastly Compute static site"
language = "javascript"
manifest_version = 3
name = "InstantAura-ImposterGame1"
service_id = "LRsemB0k6ZnxesZSd5Rh5w"

[local_server]

  [local_server.kv_stores]

    [local_server.kv_stores.InstantAura-ImposterGame1-content]
      file = "./static-publisher/kvstore.json"
      format = "json"

[scripts]
  build = "npm run build"

[setup]

  [setup.kv_stores]

    [setup.kv_stores.InstantAura-ImposterGame1-content]
